# Generated by Django 4.2.7 on 2023-12-02 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment_admin',
            field=models.TextField(blank=True, help_text="Указать комментарий при смене статуса на 'Принята в работу'", verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image_admin',
            field=models.ImageField(blank=True, help_text="Указать фото дизайна при смене статуса на 'Выполнено'", upload_to='images_admin/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])], verbose_name='Фотография дизайна'),
        ),
    ]
