  version: "3.9"
  services:
    django-app:
      build:
        context: .
        dockerfile: Dockerfile
      command: python3.10 manage.py runserver 0.0.0.0:8001
      volumes:
        - .:/design
      ports:
        - "8001:8001"